/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiSigWallet } from "./MultiSigWallet";
export * as factories from "./factories";
export { MultiSigWallet__factory } from "./factories/MultiSigWallet__factory";
